services:
  - type: web
    name: star-health-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --threads 8 --timeout 0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
